import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { DM_Sans } from "next/font/google";
import { Libre_Franklin } from "next/font/google";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm_sans",
});
const libre_franklin = Libre_Franklin({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-libre_franklin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.variable + " " + libre_franklin.variable}>
        <header className="flex items-center justify-between px-6 py-12 bg-black text-white">
          <Link className="flex items-center" href="/">
            <span className="text-lg font-bold">Next.js</span>
          </Link>
          <nav className="hidden md:flex space-x-4">
            <Link className="hover:underline" href="/">
              Home
            </Link>
            <Link className="hover:underline" href="/about">
              About
            </Link>
          </nav>
        </header>

        {children}

        <footer className="bg-black text-white px-6 py-12">
          <div className="container mx-auto flex justify-between items-center">
            <div className="space-x-4">
              <Link className="hover:underline" href="/about">
                About
              </Link>
            </div>
            <p className="text-sm">© 2024 Next.js All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
